name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: "frontend: npm install"
        run: npm install --prefix frontend
      - name: "frontend: npm test"
        run: npm test --prefix frontend
      - name: "build frontend"
        run: npm run build:frontend
      - name: "backend: npm install"
        run: npm install
      - name: "backend: npm run lint"
        run: npm run lint
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
      - name: "backend: npm test"
        env:
          PORT: 3001
          TEST_MONGODB_URI: mongodb://localhost:27017/db
          SECRET_KEY: secret
        run: npm test
      - name: e2e tests
        env:
          PORT: 3001
          MONGODB_URI: mongodb://localhost:27017/db-e2e
          SECRET_KEY: secret
        uses: cypress-io/github-action@v2
        with:
          command: npm run e2e:test --prefix frontend
          start: npm start
          wait-on: http://localhost:3001
      # If the e2e tests fail, upload the videos and screenshots recorded by Cypress
      # as artifacts
      - name: Upload Cypress videos as artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: frontend/cypress/videos
      - name: Upload Cypress screenshots as artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: deployment to Heroku
        if: github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: fast-forest-79552
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: https://fast-forest-79552.herokuapp.com/health
          checkstring: ok
          rollbackonhealthcheckfailed: true
  tag_release:
    needs: [build, deploy]
    if: github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
